name: financial_assistant
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  telephony: ^0.2.0

  go_router: ^10.1.2
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2 
  bloc_concurrency: ^0.2.2
  shared_preferences: ^2.2.1
  equatable: ^2.0.5
  either_dart: ^1.0.0
  permission_handler: ^11.0.1
  intl: ^0.18.1

  flutter_svg: ^2.0.7
  pull_to_refresh: ^2.0.0
  animated_text_kit: ^4.2.1
  dropdown_search: ^5.0.5 
  responsive_builder: ^0.4.1
  liquid_pull_to_refresh: ^3.0.1
  introduction_screen: ^3.1.12
  loading_animation_widget: ^1.2.0+4 
  syncfusion_flutter_charts: ^23.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/


